# Hugo build configuration for Netlify 
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "npm ci --no-audit --no-fund && mise x hugo-extended@0.160.1 -- hugo --cleanDestinationDir"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.160.1"
  HUGO_ENV = "production"
