# Hugo build configuration for Netlify 
# (https://gohugo.io/host-and-deploy/host-on-netlify/)

# Default build settings
[build]
  publish = "public"
  command = "npm ci --no-audit --no-fund && hugo --cleanDestinationDir"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.160.1"
  HUGO_ENV = "production"
